### ISSUE TITLE
Job scheduling

### ISSUE THREAD

**Issue by caolan** [iilab/ltfhc-next#12]
This currently relies on users logging in at appropriate times (both the previous timeframe to generate the next job, and the current timeframe for the job to run), meaning jobs can be missed.

- I'd recommend either adding a cron job to generate reports and post to couchdb
- or, preferably, add a button to the reports page to generate/regenerate a report before editing and approval so it can be done and repeated at any time as data comes in

**Comment by jmatsushita** [comment]
Button (+ dropdown to select the timerange) is a go!

**Comment by caolan** [comment]
If we're adding the ability to generate report documents on demand I think we should add the ability to delete reports (possibly limited to unapproved reports only).

**Comment by jmatsushita** [comment]
Agreed!

**Comment by caolan** [comment]
Closing in favour of #29
