### ISSUE TITLE
Automate building of reports_schema.js

### ISSUE THREAD

**Issue by caolan** [iilab/ltfhc-next#15]
Currently this is a hand-built concatenated list of relevant schema information based on the reports schema files.

It is also saved to two separate locations based on country and copied to reports_schema.js depending on which is being deployed - this part could be solved by #14 should we choose to go that route.

**Comment by caolan** [comment]
This results in quite a different file being produced - it contains the same reports but I'm noticing different properties for translations. I suspect that the reports_schema_cd.js just hadn't been kept up to date with the reports in schema/reports. @jmatsushita it would be good if you could just sanity check the result here too, since I don't know which is authoritative.

**Comment by jmatsushita** [comment]
I need to kanso push twice for updates to individual reports to be taken into account.

**Comment by jmatsushita** [comment]
@caolan bump. This can be worked around in dev, but it's a problem for updates in the field...
