### ISSUE TITLE
Separate schema definitions from presentation (layout property)

### ISSUE THREAD

**Issue by caolan** [iilab/ltfhc-next#17]
Add layout property to schema definitions and use this to generate the approprate form tables.
Create form rendering code based on spreadsheet.js so we can extend it to accommodate future requirements (such as multiple tables per form, rendering based on layout property, disabled cells etc).

Perhaps something along the following lines (exact format TBD):

```js
{
    ...,
    layout: {
        rows: [
                [{label: 'A'},     {label: 'B'},              {label: 'C'}]  
                [{label: 'foo'},   {field: 'doc.property'},   {field: 'doc.property2'}]  
                [{label: 'bar'},   {field: 'doc.property'},   {disabled: true}]
                [{label: 'TOTAL'}, {calculated: '1 + 2 + 3'}, {disabled: true}]  
        ]
    }
}
```

This ticket is for basic rendering only (to match current functionality), disabled and calculated fields add to above example for illustrative purposes only.

**Comment by caolan** [comment]
Instead of field, we'll use `{row: ..., col: ...}` to refer to the intersection of a row and column

**Comment by jmatsushita** [comment]
```
{
    ...,
    layout: [
        { type: 'disabled', row:..., col:... },
        { type: 'super_report', row:..., col:... },
        { type: 'complex_header', rows: [
                [{label: 'Gender', colspan: 2}],
                [{label: 'M'}, {label: 'F'}]
        ]
}
```

**Comment by caolan** [comment]
In the end we've gone with a hybrid system using the overrides property described by @jmatsushita above, and `parent` and `parent_title` for handling multiple tables on one report page.
