### ISSUE TITLE
New reports table

### ISSUE THREAD

**Issue by caolan** [iilab/ltfhc-next#29]
This issue replaces #12 

This aims to remove the report scheduling code currently in place with UI improvements.

* The reports page will remove the combined approved/unapproved tables at the top of the page
* All reports will be listed in a table under their headings
* This table will display the last 12 reporting periods, or up until the first visit document was recorded if that is less
* For the current period, a 'preview' button will be display which shows the report_calculated view
* For past periods:
    * If there is no report document, display a 'generate' button (red) which will create the report doc
    * If is an unapproved report, display an 'edit' button and a 'delete' button (which will revert to the
      above generate button state)
    * If there is an approved report display it with an 'approved' label and no buttons
* The visibility of these tables should be toggled by clicking the report header, with only one table displaying at a time
* If there are reports to be generated (the report table has rows which would display a generate button) it should be indicated in the report's header so the user knows to click through and view the table.

**Comment by caolan** [comment]
Q: if we display the report-to-be-generated status in the heading then users are likely to see that indicator for a long time while the past 12 report periods are slowly filled up and drop off the end of the table, making it fairly useless for the first year - the UI may need some more thought there

**Comment by caolan** [comment]
@jmatsushita should the indicator for missing reports be present when a report has not been generated or when there are any unapproved (or not generated) reports for a previous period? - I'm going to assume the latter for now but clarification would be good

**Comment by jmatsushita** [comment]
Yes this "todo" indicator should be present where report have not been generated as well as if there are any unapproved reports since the first report.

**Comment by caolan** [comment]
@jmatsushita ok, I think this is ready to review now
